name: Reddit Worker

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        working-directory: ./excer
        run: npm install
        
      - name: Run worker
        working-directory: ./excer
        env:
          KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
          KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
          WORKER_SECRET: ${{ secrets.WORKER_SECRET }}
          VERCEL_APP_URL: ${{ secrets.VERCEL_APP_URL }}
        run: node scripts/github-worker.js