name: Reddit Worker

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        type: boolean
        required: false
        default: false

jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
# Using external Redis instead of local Redis service

      - name: Install dependencies
        working-directory: ./excer
        run: |
          npm install
          npm install -g tsx
        
      - name: Run worker
        working-directory: ./excer
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          WORKER_SECRET: ${{ secrets.WORKER_SECRET }}
          VERCEL_APP_URL: ${{ secrets.VERCEL_APP_URL }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: tsx scripts/github-worker.ts